### ISSUE TITLE
Middle/Ctrl click no longer opens bookmarks in the background in Chrome 107

### ISSUE THREAD

**Issue by pingshunhuangalex** [windviki/vBookmarks#26] opened 2022-11-04 09:52 UTC
Not sure if this extension is still maintained, but I'm gonna try my luck here.

With the upgrade to Chrome 107, I noticed that the middle/ctrl-click no longer opens bookmarks in the background, even if the option is toggled in settings. Thanks.

**Comment by windviki** [comment] 2023-02-02 03:54
Will be fixed in v3.3.

**Closed** 2023-02-02 07:25 UTC

**Comment by pingshunhuangalex** [comment] 2023-02-03 06:14
Hey @windviki 

Thanks for fixing the extension.

Just had a go with the latest version and found that the middle click on folders (not individual bookmarks) is still broken.

Also, there's now an annoying delay when you click on the icon (to open the bookmark dropdown). Not sure if it's related to your changes.

Thanks again for keeping the extension alive.

**Comment by windviki** [comment] 2023-02-06 07:43
Yes, I didn't notice the feature "middle click on folders". Will be fixed in next version.
---
As for the "delay" you mentioned, I think maybe it's caused by popup height resetting for current tab (to avoid double scroll bar). It's the only addition check in this version.
But on my device, there's no obvious delay. We can wait for a better solution.

**Comment by windviki** [comment] 2023-03-29 08:58
> Yes, I didn't notice the feature "middle click on folders". Will be fixed in next version.
> 
> As for the "delay" you mentioned, I think maybe it's caused by popup height resetting for current tab (to avoid double scroll bar). It's the only addition check in this version. But on my device, there's no obvious delay. We can wait for a better solution.

Fixed in v3.4
